### PR TITLE
Quantity font size

### LINKED ISSUE #184: Pokeball Quantity
## Expected Behavior

Pokeball quantity number should stay relatively the same spacing between its container

## Actual/Current Behavior

The numbers overflow when more characters are added (3 digits or more)

## Steps to Reproduce the Problem

  1. Buy 100 pokemons

### PR DESCRIPTION
**Pull request by JayDampitan**
## Changes
1. Adjust font size of quantity to fit the pokeball container. 

Closes #184

### CODE REVIEW

File: pokeapp/src/components/PokemonCard.js [hunk 1]
```diff
@@ -127,7 +130,15 @@ const PokemonCard = ({
...
-          <h4 className="pokeball-font">{pokemon.quantity > 0 ? `x${pokemon.quantity}` : ""}</h4>
+          <h4
+            className={
+              pokemon.quantity >= 100
+                ? "pokeball-font-hundreds"
+                : "pokeball-font"
+            }
+          >
+            {pokemon.quantity > 0 ? `x${pokemon.quantity}` : ""}
+          </h4>
```
Comment (krferrell) [inline pokeapp/src/components/PokemonCard.js:141]: Nice work Jay!

**Review by krferrell — APPROVED** [review]
Nicely done.

File: pokeapp/src/styling/components/_pokemon-card.scss [hunk 2]
```diff
@@ -104,12 +104,15 @@
 .pokeball-hidden {
   position: relative;
   border-radius: 50%;
-  width: 25px;
-  height: 25px;
+  min-width: 25px;
+  min-height: 25px;
+  max-width: 25px;
+  max-height: 25px;
```
Comment (Lap343) [inline pokeapp/src/styling/components/_pokemon-card.scss:110]: Wouldn't you just use height and width to set the height and width rather than two settings for each?

File: pokeapp/src/styling/components/_pokemon-card.scss [hunk 3]
```diff
@@ -127,8 +130,23 @@
...
+    font-size: 13px;
     color: $quantity-color;
     z-index: 100;
+    display: flex;
+    justify-content: center;
+    align-items: center;
+    padding: 2px;
+
+    &.pokeball-font-hundreds {
+      color: $quantity-color;
```
Comment (BlackCubes) [inline pokeapp/src/styling/components/_pokemon-card.scss:142]: YO! You keep this SASS clean!!!!!!!!!!!!!!!!!!!!!!!!

**Review by BlackCubes — APPROVED** [review]
Looks noice!

File: pokeapp/src/styling/components/_pokemon-card.scss [hunk 4]
```diff
@@ -104,10 +104,8 @@
 .pokeball-hidden {
   position: relative;
   border-radius: 50%;
-  min-width: 25px;
-  min-height: 25px;
-  max-width: 25px;
-  max-height: 25px;
+  width: 25px;
+  height: 25px;
```
Comment (Lap343) [inline pokeapp/src/styling/components/_pokemon-card.scss]: Very nice

**Review by Lap343 — APPROVED** [review]
Great job
